### ISSUE TITLE
PropertywiseEquatable is by field

### ISSUE THREAD

**Issue by johnsparrowuk** [thedmi/Equ#1]
Great util! PropertywiseEquatable.cs contains:

`private static readonly MemberwiseEqualityComparer<TSelf> _equalityComparer = MemberwiseEqualityComparer<TSelf>.ByFields;`

..and I guess it should be `.ByProperties`?

**Comment by thedmi** [comment]
Yes, you're absolutely right, thanks for the bug report. I fixed it on master, the fix will be contained in release 1.0.3.
