### ISSUE TITLE
Add netstandard2.0 build target framework

### ISSUE THREAD

**Issue by herebebeasties** [thedmi/Equ#13]
See https://docs.microsoft.com/en-us/dotnet/standard/net-standard, specifically:
> [...] targeting lower .NET Standard versions introduces a number of support dependencies. If your project targets .NET Standard 1.x, we recommend that you also target .NET Standard 2.0. This simplifies the dependency graph for users of your library that run on .NET Standard 2.0 compatible frameworks, and it reduces the number of packages they need to download.

This would avoid pulling in the big mass of `System.*` DLLs which pollute apps output folders and can cause various issues downstream in your build, which are all resolved by using 2.0. (Can provide more detail on this if you're interested - the CoreFX / MSBuild projects on github have various issues triggered by this.)

**Comment by ruler501** [comment]
It doesn't seem that this project is seeing any active work from the original developer. I have a fork that is available on Nuget with a couple extra features and bug fixes. I just added a version with netstandard2.0 build configuration. Package is ruler501.Equ and it's available on github at https://github.com/ruler501/Equ
