### ISSUE TITLE
Compile assembly with strong name

### ISSUE THREAD

**Issue by gasparnagy** [thedmi/Equ#14]
I would like to use the lib in a project, where (because of other constraints), I would need it to be signed. 
Do you have a solution for this? Can you make a new release in NuGet if I send a PR with the signing?

**Comment by thedmi** [comment]
I'd need to look into this, I don't know much yet about library signing. A PR would be a great start!

**Comment by gasparnagy** [comment]
@thedmi sure! please check #19.
