### ISSUE TITLE
Support for .net 4.6.1/2

### ISSUE THREAD

**Issue by joefeser** [thedmi/Equ#5]
It appears that you are only targeting .net core (at least the nuget package only supports it).

Do you plan on supporting the .net framework going forward?

**Comment by thedmi** [comment]
Equ is a .NET Standard 1.5 library, so it runs anywhere .NET Standard 1.5 is supported:

- .NET Framework 4.6.1 and newer
- .NET Core 1.0 and newer
- Mono 4.6 and newer
- Xamarin.Android 7.0 and newer
- Xamarin.iOS 10.0 and newer

See https://docs.microsoft.com/en-us/dotnet/standard/net-standard for a complete list of .NET Standard library compatibility.

**Comment by joefeser** [comment]
Nuget on vs.net 2015 will not let me add the package. I will try 2017 and see what happens. We are stuck with 2015 at work.

**Comment by thedmi** [comment]
According to the link I posted above, .NET Framework requires the .NET Core SDK to be able to use .NET Standard libraries. That being said, the .NET Core SDK is just required to *compile* the application, it will then *run* on a .NET Framework runtime without any .NET Core stuff installed.

**Comment by thedmi** [comment]
Also, if you don't get it to run, you could try Equ 1.0.4, which was the last version before the transition to .NET Standard and still targets .NET Framework. Note though that the 1.x branch won't receive any fixes anymore.
